/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./openzeppelin";
export type { openzeppelin };
import type * as test from "./test";
export type { test };
export type { LendingPool } from "./LendingPool";
export type { LendingPoolBridge } from "./LendingPoolBridge";
export type { PriceOracle } from "./PriceOracle";
export type { WrappedToken } from "./WrappedToken";
